import type { Metadata } from "next";
import {cookies} from "next/headers";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  const token = cookies().get("Authorization");
  console.log(token);
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
